### ISSUE TITLE
Sonos_Control_and_State example code

### ISSUE THREAD

**Issue by tadurham** [tmittet/sonos#1]
I can't seem to 'verify' the example code. I get an error for 'ethConnectError' not declared in scope. This is solved by adding `EthernetClient ethConnectError;`

Then fails with error `Sonos_Control_and_State:85: error: no matching function for call to 'SonosUPnP::SonosUPnP(EthernetClient&, EthernetClient&)'
 SonosUPnP g_sonos = SonosUPnP(g_ethClient, ethConnectError);`

**Comment by philipoos76** [comment]
i had the same problem as tadurham and then the same compilation error for g_sonos not declared in this scope. Being a novice i gave up at this point.

**Comment by buestad** [comment]
Just add a & in front of ethConnectError. worked for me...

`EthernetClient g_ethClient;`
`SonosUPnP g_sonos = SonosUPnP(g_ethClient, &ethConnectError);`

**Comment by tadurham** [comment]
This resolved my issue. Thank you @buestad.
