### ISSUE TITLE
Is this library still working with latest Sonos firmware?

### ISSUE THREAD

**Issue by nitech** [tmittet/sonos#5]
Hi, I am trying to make this library work with my Sonos Play 1 Speakers, and I am not sure where things stop. 

When I for instance try to run `g_sonos.play(g_sonosLivingrIP);`, this is what `void SonosUPnP::ethClient_write(const char *data)` outputs: 

```xml
POST Host: 192.168.2.212:1400
Content-Length: 266
#"

<u: xmlns:u="urn:"><Speed>1</Speed></u:>
```

Is this correct? 

I have also tried out a .Net library called SonosSharp, which sends the following POST data when "play"-ing: 

```xml
POST http://192.168.2.212:1400/MediaRenderer/AVTransport/Control HTTP/1.1
Content-Type: text/xml
SOAPAction: "urn:schemas-upnp-org:service:AVTransport:1#Play"
Host: 192.168.2.212:1400
Content-Length: 244
Expect: 100-continue
TerminalId: Vekt2-Nede

<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Body>
         <u:Play xmlns:u="urn:schemas-upnp-org:service:AVTransport:1">
            <Speed>1</Speed>
            <InstanceID>0</InstanceID>
         </u:Play>
    </s:Body>
</s:Envelope>
```

**Comment by nitech** [comment]
Hmm... it seems that somehow most of the variables that make the soap body is not included, right?

**Comment by nitech** [comment]
I Serial.print-ed within `void SonosUPnP::ethClient_write_P(PGM_P data_P, char *buffer, size_t bufferSize)`and got the following: 

``` xml
POST /MediaRenderer/AVTransport/Control HTTP/1.1
Host: 192.168.2.212:1400
Content-Type: text/xml; charset="utf-8"
Content-Length: 266
SOAPAction: "urn:schemas-upnp-org:service:AVTransport:1#Play"
Connection: close

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/sooap/envelope/" s:encodingStyle="http://schemas.xmllsoap.org/soap/encoding/">
<s:Body>
<u:Play xmlns:u="urn:schemas-upnp-org:service:AVTransport:1">
<InstanceID>0</InstanceID>
<Speed>1</Speed>
</u:Play>
</s:Body>
</s:Envelope>
```

Which to me looks correct. 

I might be down to the issue here: The original code said the following on SonosUPnP.cpp:737: 

```
    // strncpy_P ?? 
    strlcpy_P(buffer, data_P + dataPos, bufferSize);
```

It didn't want to compile, saying: 

```
SonosUPnP.cpp: In member function 'void SonosUPnP::ethClient_write_P(const char*, char*, size_t)':
SonosUPnP.cpp:738:51: error: 'strlcpy_P' was not declared in this scope
```

So I tried replacing it with `strncpy_P` (just blindly attempting stuff), which stopped the compile error, but probably introduced the bug I am experiencing. 

Any idea if I am on the right track, and what is the reason of why `strlcpy_P` is "not declared in scope"?

It seems `strlcpy_P` comes from `pgmspace.h` which the compiler complained about earlier. I just found one on the net and included it, but I now realize that one I found doesn't have `strlcpy_P`. I also read somewhere that `pgmspace.h` was supposed to be bundled withe the core arduino stuff.

**Comment by nitech** [comment]
Okay. This thread is getting long. I downloaded `pgmspace.h` from here (https://raw.githubusercontent.com/arduino/Arduino/master/hardware/arduino/sam/cores/arduino/avr/pgmspace.h) and used that instead. Now, `strlcpy_P` works, and from what I can see, there is no error, but still the player won't play.

Is there any way to get the complete package that is posted over HTTP, so I can possibly inspect what is wrong?

**Comment by bopeterson** [comment]
I haven't used this library in a while but I think it should work with the latest firmware. When I made my own [Arduino Sonos library](https://github.com/bopeterson/sonos-esp) I learned a lot from this simple code http://jpmens.net/2010/03/16/sonos-pause-switch/, from https://github.com/Zepheus/esp8266-sonos-rfid and finally from tmittet/sonos

**Comment by nitech** [comment]
Thanks @bopeterson. Your links led me to other links which in total gave me the understanding of UPnP and the Sonos API I needed to get something working. 

Meanwhile, @antonmeyer made me aware of his port of this library to ESP8266, see issue #3 and the fork at https://github.com/antonmeyer/sonos

Here are some of the links that helped me understand: 

http://openrb.com/sonos-control-from-logic-machine/
http://forum.logicmachine.net/printthread.php?tid=144
http://blog.travelmarx.com/2011/01/extracting-sonos-playlist-simple-sonos.html

**Comment by bopeterson** [comment]
Great that I could be of some help, and thanks for the links below.

/Bo
