### ISSUE TITLE
getVolume returns undefined value

### ISSUE THREAD

**Issue by denglend** [tmittet/sonos#8]
The version of getVolume that doesn't take a channel (pasted below) doesn't have a return statement, so the returned value is undefined.  In practice you get some random-ish value calling tihs function.

```
uint8_t SonosUPnP::getVolume(IPAddress speakerIP)
{
  getVolume(speakerIP, SONOS_CHANNEL_MASTER);
}
```

Adding a return to the one line of code fixes the issue.

**Comment by tmittet** [comment]
Thanks for reporting, should be fixed now
